name: Deploy to Netlify

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Node.js (this step installs Node.js 16)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Navigate to the frontend directory (champion-compass)
    - name: Change directory to champion-compass
      run: cd champion-compass

    # Step 4: Install project dependencies (inside champion-compass)
    - name: Install dependencies
      working-directory: champion-compass
      run: npm install

    # Step 5: Build your site (this will run 'npm run build' in the correct directory)
    - name: Build the project
      working-directory: champion-compass
      run: npm run build

    # Step 6: Deploy to Netlify
    - name: Deploy to Netlify
      working-directory: champion-compass
      run: npx netlify deploy --prod --auth ${{ secrets.nfp_wdngw5B9FC3shreSTX6hhmo3fcYTyQt7bec1 }} --site ${{ secrets.dc9b9f41-8ce8-49bd-bfa5-1ccf172c756c }}
